[package]
name = "rustsweep"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.22", features = ["blocking"] }
clap = { version = "4.5.41", features = ["derive"] }
colored = "3.0.0"
iptools = "0.3.0"
popen_rs = "0.1.0"
regex = "1.11.1"
